name: Build docker and upload to registry

on:
  push:
    tags:
      # strict semver regex
      - v[1-9]+.[0-9]+.[0-9]+* # allows prerelease tags

jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-18.04
    steps:
      - name: Install dependencies
        run: |
          sudo snap install doctl
          sudo snap connect doctl:dot-docker

      - name: Configure auth for Digital Ocean
        run: |
          doctl auth init -t ${{ secrets.CIRCLES_CI_DO_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get ref
        id: parse_ref
        run: |
          echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

      - name: Digital Ocean Registry login
        run: |
          doctl registry login

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            registry.digitalocean.com/circles-registry/safe-relay-service:${{ steps.parse_ref.outputs.tag }}
            joincircles/safe-relay-service:latest
            joincircles/safe-relay-service:${{ steps.parse_ref.outputs.tag }}
